Added Java translation
HowProgrammingWorks/Metaprogramming pull request #2
Opened 2017-06-02 16:20 UTC by igorIsyutin

Translate 1 part of Metaprogramming. Teamwork with SergFrolov

2017-06-07 10:30 UTC, tshemsedinov requested changes
Use linter

2017-06-07 10:30 UTC, tshemsedinov commented on Java/src/1-extract-metadata/1-filter-simple.java
> +}
Add line break at the EOF

2017-06-07 10:30 UTC, tshemsedinov commented on Java/src/1-extract-metadata/1-filter-simple.java
> +            "Marcus Aurelius Antoninus Augustus",
Indentation

2018-09-23 19:50 UTC, lundibundi commented
Closed due to an absence of activity.

2018-09-23 19:50 UTC, closed without merging